/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import inmobiliaria.Conexion;
import inmobiliaria.Inmueble;
import inmobiliaria.InmuebleData;
import inmobiliaria.PersonaData;
import inmobiliaria.Persona;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static vistas.GestionInmuebles.jDesktopPane1;

/**
 *
 * @author pedro
 */
public class AgregarInmueble extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarInmueble
     * @throws java.lang.ClassNotFoundException
     */
    public AgregarInmueble() {
        initComponents();
        this.personaPropietaria.removeAllItems();
        //try{
        //Conexion con = new Conexion("jdbc:mysql://localhost/inmobiliaria2","root","");
        PersonaData pd = new PersonaData();
        List<Persona> personas = pd.obtenerPersonas();
        int i = 0;
        while(personas.size()>i){
            
            this.personaPropietaria.addItem(personas.get(i).getNombreCompleto());
            i++;
        }
        
        //} catch (Exception e) {
           // System.out.println("Se agrego las personas de la base de datos al combobox " + e.getMessage());
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cantAmbientes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        disponibilidad = new javax.swing.JCheckBox();
        personaPropietaria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        agregarBoton = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        setClosable(true);
        setTitle("Agregar Inmueble");

        jLabel1.setText("Direccion:");

        jLabel2.setText("Cantidad de ambientes:");

        disponibilidad.setText("Disponible");

        personaPropietaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Persona propietaria:");

        agregarBoton.setText("Agregar");
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibilidad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoDireccion)
                                .addComponent(cantAmbientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(personaPropietaria, 0, 241, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantAmbientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaPropietaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(disponibilidad)
                .addGap(18, 18, 18)
                .addComponent(agregarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        InmuebleData id = new InmuebleData();
        Inmueble inm = new Inmueble();
        PersonaData pd = new PersonaData();
        if(campoDireccion.getText().trim().length()!=0 && this.cantAmbientes.getText().trim().length() != 0){
        inm.setDireccion(this.campoDireccion.getText().trim());
        inm.setCantAmbientes(Integer.valueOf(this.cantAmbientes.getText().trim()));
        inm.setDisponibilidad(this.disponibilidad.isSelected());
        inm.setpersona(pd.obtenerPersonas(personaPropietaria.getSelectedItem().toString()));
        id.guardarInmueble(inm);
        
        this.dispose();
        
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        TablaDeInmueble ti = new TablaDeInmueble();
        ti.setVisible(true);
        jDesktopPane1.add(ti);
        
        System.out.println("Se agrego con exito el inmueble");
        
        } else {
           JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para continuar");;}
        
    }//GEN-LAST:event_agregarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField cantAmbientes;
    private javax.swing.JCheckBox disponibilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> personaPropietaria;
    // End of variables declaration//GEN-END:variables
}
