/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import inmobiliaria.Alquiler;
import inmobiliaria.AlquilerData;
import inmobiliaria.Inmueble;
import inmobiliaria.InmuebleData;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pedro
 */
public class GestionInmuebles extends javax.swing.JFrame {

    /**
     * Creates new form GestionInmuebles
     */
    public GestionInmuebles(){
        initComponents();


        
         TablaDeInmueble tim = new TablaDeInmueble();
        tim.setVisible(true);
        this.jDesktopPane1.add(tim);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        boton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        buscar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        eliminarBoton = new javax.swing.JMenuItem();
        eliminarSeleccion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jMenu1.setText("Agregar");

        boton.setText("Agregar un Inmueble");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        jMenu1.add(boton);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Buscar");

        buscar.setText("Realizar una busqueda");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jMenu2.add(buscar);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Eliminar");

        eliminarBoton.setText("Por direccion");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarBoton);

        eliminarSeleccion.setText("Por seleccion");
        eliminarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSeleccionActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarSeleccion);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        //try {
           // this.jDesktopPane1.removeAll();
        //this.jDesktopPane1.repaint();
        
            AgregarInmueble ai = new AgregarInmueble();
            ai.setVisible(true);
            ai.setBounds(0, 0, 500, 300);
            this.jDesktopPane1.add(ai);
            ai.moveToFront();
            
        //} catch (ClassNotFoundException ex) {
        //    System.out.print("Me voy a dormir si esto no funciona");
        //}
        
        
       
    }//GEN-LAST:event_botonActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        TablaBuscar tb = new TablaBuscar();
        tb.setVisible(true);
        this.jDesktopPane1.add(tb);
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        EliminarInmueble ei = new EliminarInmueble();
        ei.setVisible(true);
        this.jDesktopPane1.add(ei);
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void eliminarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSeleccionActionPerformed
          jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        EliminarSeleccion es = new EliminarSeleccion();
        es.setVisible(true);
        this.jDesktopPane1.add(es);
    }//GEN-LAST:event_eliminarSeleccionActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInmuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInmuebles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem boton;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenuItem eliminarBoton;
    private javax.swing.JMenuItem eliminarSeleccion;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
