/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author pedro
 */
public class GestionAlquileres extends javax.swing.JFrame {

    /**
     * Creates new form GestionAlquileres
     */
    public GestionAlquileres() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AlquilerTabla at = new AlquilerTabla();
        escritorio.add(at);
        at.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        buscarDB = new javax.swing.JMenuItem();
        buscarPB = new javax.swing.JMenuItem();
        buscarDyPB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        eliminarDB = new javax.swing.JMenuItem();
        eliminarPB = new javax.swing.JMenuItem();
        eliminarDYP = new javax.swing.JMenuItem();
        eliminarSeleccionA = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        modificarO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jMenu1.setText("Agregar");

        jMenuItem1.setText("Agregar un alquiler");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar");

        buscarDB.setText("Buscar alquiler por dirección");
        buscarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDBActionPerformed(evt);
            }
        });
        jMenu2.add(buscarDB);

        buscarPB.setText("Buscar alquiler por persona");
        buscarPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPBActionPerformed(evt);
            }
        });
        jMenu2.add(buscarPB);

        buscarDyPB.setText("Buscar por direccion y persona");
        buscarDyPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDyPBActionPerformed(evt);
            }
        });
        jMenu2.add(buscarDyPB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Eliminar");

        eliminarDB.setText("Eliminar por direccion");
        eliminarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDBActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarDB);

        eliminarPB.setText("Eliminar por persona");
        eliminarPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPBActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarPB);

        eliminarDYP.setText("Eliminar por direccion y persona");
        eliminarDYP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDYPActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarDYP);

        eliminarSeleccionA.setText("Eliminar por selección");
        eliminarSeleccionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSeleccionAActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarSeleccionA);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Modificar");

        modificarO.setText("Modificar observacion");
        modificarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarOActionPerformed(evt);
            }
        });
        jMenu4.add(modificarO);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AgregarAlquiler aa = new AgregarAlquiler();
        escritorio.add(aa);
        aa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void buscarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDBActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarAlquileres ba = new BuscarAlquileres();
        escritorio.add(ba);
        ba.setVisible(true);
    }//GEN-LAST:event_buscarDBActionPerformed

    private void buscarPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPBActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarAlquileresPersona bap = new BuscarAlquileresPersona();
        escritorio.add(bap);
        bap.setVisible(true);
    }//GEN-LAST:event_buscarPBActionPerformed

    private void buscarDyPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDyPBActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        BuscarAlquileresDYP dyp = new BuscarAlquileresDYP();
        escritorio.add(dyp);
        dyp.setVisible(true);
    }//GEN-LAST:event_buscarDyPBActionPerformed

    private void eliminarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDBActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        EliminarAlquileresD ead = new EliminarAlquileresD();
        escritorio.add(ead);
        ead.setVisible(true);
    }//GEN-LAST:event_eliminarDBActionPerformed

    private void eliminarPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPBActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        EliminarAlquileresP eap = new EliminarAlquileresP();
        escritorio.add(eap);
        eap.setVisible(true);
    }//GEN-LAST:event_eliminarPBActionPerformed

    private void eliminarDYPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDYPActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        EliminarAlquileresDYP eap = new EliminarAlquileresDYP();
        escritorio.add(eap);
        eap.setVisible(true);
    }//GEN-LAST:event_eliminarDYPActionPerformed

    private void eliminarSeleccionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSeleccionAActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        EliminarASeleccion eap = new EliminarASeleccion();
        escritorio.add(eap);
        eap.setVisible(true);
    }//GEN-LAST:event_eliminarSeleccionAActionPerformed

    private void modificarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarOActionPerformed
               escritorio.removeAll();
        escritorio.repaint();
        ModificarO eap = new ModificarO();
        escritorio.add(eap);
        eap.setVisible(true);
    }//GEN-LAST:event_modificarOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAlquileres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarDB;
    private javax.swing.JMenuItem buscarDyPB;
    private javax.swing.JMenuItem buscarPB;
    private javax.swing.JMenuItem eliminarDB;
    private javax.swing.JMenuItem eliminarDYP;
    private javax.swing.JMenuItem eliminarPB;
    private javax.swing.JMenuItem eliminarSeleccionA;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem modificarO;
    // End of variables declaration//GEN-END:variables
}
