/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import inmobiliaria.Conexion;
import inmobiliaria.Inmueble;
import inmobiliaria.InmuebleData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class TablaDeInmueble extends javax.swing.JInternalFrame {

    private  DefaultTableModel modelo;
    private InmuebleData inmd;
    /**
     * Creates new form TablaDeInmueble
     */
    public TablaDeInmueble(){
        initComponents();
        
        inmd = new InmuebleData();
        this.cargarTabla();
        
        
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInmuebles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Direccion", "Cantidad de Ambientes", "Disponibilidad", "Persona propietaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaInmuebles);
        if (tablaInmuebles.getColumnModel().getColumnCount() > 0) {
            tablaInmuebles.getColumnModel().getColumn(0).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(0).setHeaderValue("Direccion");
            tablaInmuebles.getColumnModel().getColumn(1).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(1).setHeaderValue("Cantidad de Ambientes");
            tablaInmuebles.getColumnModel().getColumn(2).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(2).setHeaderValue("Disponibilidad");
            tablaInmuebles.getColumnModel().getColumn(3).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(3).setHeaderValue("Persona propietaria");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 980, 390));

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inmuebles");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 15));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 129, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInmuebles;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        List<Inmueble> inm = inmd.obtenerInmuebles();
        
        if (inm == null || inm.isEmpty()) {   
      JOptionPane.showMessageDialog(null, "No hay inmuebles cargados en la base de datos");
        } else {
            modelo = (DefaultTableModel) tablaInmuebles.getModel();
            
            
            modelo.setRowCount(0);
            Object[] fila = new Object[4];

            for (int i = 0; i < inm.size(); i++) {
                fila[0] = inm.get(i).getDireccion().toUpperCase();
                fila[1] = inm.get(i).getCantAmbientes();
                fila[2] = inm.get(i).isDisponibilidad();
                fila[3] = inm.get(i).getpersona().getNombreCompleto().toUpperCase();
                modelo.addRow(fila);
            }
        }
    }
}
