/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Ro
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    VentanaPrincipal v;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        JItem_GestionarClientes = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jitem_GestionarClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JItem_GestionarInmuebles = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JItem_GestionarAlquileres = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem7.setText("Listar");
        jMenu1.add(jMenuItem7);

        JItem_GestionarClientes.add(jMenu1);

        jMenu3.setText("Clientes");

        jitem_GestionarClientes.setText("Gestionar clientes");
        jitem_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitem_GestionarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jitem_GestionarClientes);

        JItem_GestionarClientes.add(jMenu3);

        jMenu2.setText("Inmuebles");

        JItem_GestionarInmuebles.setText("Gestionar inmuebles");
        JItem_GestionarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItem_GestionarInmueblesActionPerformed(evt);
            }
        });
        jMenu2.add(JItem_GestionarInmuebles);

        JItem_GestionarClientes.add(jMenu2);

        jMenu4.setText("Alquileres");

        JItem_GestionarAlquileres.setText("Gestionar alquileres");
        JItem_GestionarAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItem_GestionarAlquileresActionPerformed(evt);
            }
        });
        jMenu4.add(JItem_GestionarAlquileres);

        JItem_GestionarClientes.add(jMenu4);

        setJMenuBar(JItem_GestionarClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jitem_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitem_GestionarClientesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionClientes gc = new GestionClientes();
        gc.setVisible(true);
        escritorio.add(cl);
    }//GEN-LAST:event_jitem_GestionarClientesActionPerformed

    private void JItem_GestionarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItem_GestionarInmueblesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionInmuebles gi = new GestionInmuebles();
        gi.setVisible(true);
        escritorio.add(cl);
    }//GEN-LAST:event_JItem_GestionarInmueblesActionPerformed

    private void JItem_GestionarAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItem_GestionarAlquileresActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionAlquileres ga = new GestionAlquileres();
        ga.setVisible(true);
        escritorio.add(cl);
    }//GEN-LAST:event_JItem_GestionarAlquileresActionPerformed
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JItem_GestionarAlquileres;
    private javax.swing.JMenuBar JItem_GestionarClientes;
    private javax.swing.JMenuItem JItem_GestionarInmuebles;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jitem_GestionarClientes;
    // End of variables declaration//GEN-END:variables
}
